### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Kribashini** [NCAR/VAPOR#1982]
### Describe the bug
Segmentation fault (core dumped)

**Helpful additional information**
(*Please click check boxes AFTER submitting ticket*)
- [ Y] Did VAPOR crash? 
- [N ] Did you get wrong results?

**Impact**
- [x] High - User productivity significantly degraded
- [ ] Medium - User productivity partially degraded
- [ ] Low - User productivity trivially degraded

### To Reproduce
Steps to reproduce the behavior. For example:

*Additionally, please attach a session file to this ticket to easily reproduce (use File->Save Session).*

### Expected behavior
Whenever iso tab is clicked to be enabled, vapor is crashed.

### Attachments
* Can you reproduce the bug on our test data?
  * If so, which file?
  * If not, access to your data would be very helpful. If the data set is small, please zip and upload it as an attachment. If it is large, please provide instructions for how we can contact you to obtain this data.
* Please attach a session file to easily reproduce (use File->Save Session).
* Please attach any screenshots relevant to understanding the issue.

### Desktop
 - OS and version: [e.g. Ubuntu 16.04]
 - Version: [e.g. Vapor 2.6.0]

### Additional context
Unable to load library icui18n "Cannot load library icui18n: (icui18n: cannot open shared object file: No such file or directory)"

**Comment by StasJ** [comment]
Hi, we are sorry to hear this is causing you trouble, however the current release is version 3.1 and we are no longer actively supporting version 2.6. These new versions can be downloaded at [https://www.vapor.ucar.edu/](https://www.vapor.ucar.edu/). Please give it a try and it should fix the issue for you.

**Comment by Kribashini** [comment]
Hi 
I downloaded the latest version. However I am getting this issue 

Unable to load library icui18n "Cannot load library icui18n: (icui18n: cannot open shared object file: No such file or directory)" 
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0


So the file is imported but no data is seen on the screen after enabling also.

**Comment by Kribashini** [comment]
I would like to update on the previous issue that was raised by me. 

> X Error: BadDrawable (invalid Pixmap or Window parameter) 9
> Major opcode: 62 (X_CopyArea)
> Resource id: 0x0

The above one is solved by issuing the command 
export QT_GRAPHICSSYSTEM=native

However, there seems to be a problem 
The variable is still not appearing on the image rendering window when the file is loaded. Also the histogram is seen. (The file loaded is the sample file given in the vapor webpage). Also the image is loading (base map topography), but while clicking other options like volume or iso, histogram is loaded but nothing appears on the image rendering window.

**Comment by StasJ** [comment]
Which sample dataset are you using? Could you please attach a screenshot of vapor showing the problems you described?

**Comment by Kribashini** [comment]
![Screenshot from 2019-12-13 10-20-52](https://user-images.githubusercontent.com/58763369/70770251-99252300-1d92-11ea-8649-76c707fe3af4.png)

Dataset used : SAMPLE DATA DUKU (WRF Model) from Vapor Website
